name: terraform-ci
on:
  push:
    branches: '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: v1.1.9
    - name: Validate
      run: terraform fmt -check -recursive .
